# Generated by Django 5.1.2 on 2024-11-21 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=70)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('phonenumber', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('service_type', models.CharField(choices=[('GENERAL_CHECK-UP', 'General Check-Up'), ('TEETH_CLEANING', 'Teeth Cleaning'), ('TEETH_WHITENING', 'Teeth Whitening'), ('DENTAL_IMPLANTS', 'Dental Implants'), ('ROOT_CANAL', 'Root Canal'), ('OTHER', 'Other')], default='general_check-up', max_length=50)),
                ('additonal_note', models.TextField()),
            ],
        ),
    ]
